name: Create Archive
on:
  push:
    branches:
      - main
jobs: 
  run:
    name: Add/update tag to new release
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        description: Latest
        tag-name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
